// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i12;
import 'dart:convert' as _i33;
import 'dart:io' as _i26;
import 'dart:typed_data' as _i14;

import 'package:flutter/foundation.dart' as _i30;
import 'package:flutter_bloc/flutter_bloc.dart' as _i34;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i5;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i22;
import 'package:myapp/chat/cubit/chat_cubit.dart' as _i8;
import 'package:myapp/chat/model/chat_message.dart' as _i21;
import 'package:myapp/dashboard_v2/model/insight.dart' as _i3;
import 'package:myapp/dashboard_v2/model/simple_insight.dart' as _i4;
import 'package:myapp/entry/category.dart' as _i19;
import 'package:myapp/entry/entry.dart' as _i18;
import 'package:myapp/intent_detection/models/models.dart' as _i6;
import 'package:myapp/intent_detection/services/intent_detection_service.dart'
    as _i31;
import 'package:myapp/services/ai_service.dart' as _i20;
import 'package:myapp/services/audio_recorder_service.dart' as _i23;
import 'package:myapp/services/device_id_service.dart' as _i28;
import 'package:myapp/services/entry_persistence_service.dart' as _i17;
import 'package:myapp/services/firestore_sync_service.dart' as _i27;
import 'package:myapp/services/image_storage_service.dart' as _i25;
import 'package:myapp/services/permission_service.dart' as _i15;
import 'package:myapp/services/snapshot_service.dart' as _i29;
import 'package:myapp/services/vector_store_service.dart' as _i24;
import 'package:myapp/settings/cubit/settings_cubit.dart' as _i10;
import 'package:myapp/settings/services/auth_service.dart' as _i9;
import 'package:myapp/speech_service.dart' as _i11;
import 'package:permission_handler/permission_handler.dart' as _i16;
import 'package:record/record.dart' as _i13;
import 'package:record_platform_interface/record_platform_interface.dart'
    as _i2;
import 'package:shared_preferences/shared_preferences.dart' as _i32;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAmplitude_0 extends _i1.SmartFake implements _i2.Amplitude {
  _FakeAmplitude_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComprehensiveInsight_1 extends _i1.SmartFake
    implements _i3.ComprehensiveInsight {
  _FakeComprehensiveInsight_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleInsight_2 extends _i1.SmartFake implements _i4.SimpleInsight {
  _FakeSimpleInsight_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_3 extends _i1.SmartFake implements _i5.IOSOptions {
  _FakeIOSOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_4 extends _i1.SmartFake
    implements _i5.AndroidOptions {
  _FakeAndroidOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_5 extends _i1.SmartFake implements _i5.LinuxOptions {
  _FakeLinuxOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_6 extends _i1.SmartFake
    implements _i5.WindowsOptions {
  _FakeWindowsOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_7 extends _i1.SmartFake implements _i5.WebOptions {
  _FakeWebOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppleOptions_8 extends _i1.SmartFake implements _i5.AppleOptions {
  _FakeAppleOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIntentClassification_9 extends _i1.SmartFake
    implements _i6.IntentClassification {
  _FakeIntentClassification_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_10 extends _i1.SmartFake implements _i7.Response {
  _FakeResponse_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_11 extends _i1.SmartFake
    implements _i7.StreamedResponse {
  _FakeStreamedResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatState_12 extends _i1.SmartFake implements _i8.ChatState {
  _FakeChatState_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthUser_13 extends _i1.SmartFake implements _i9.AuthUser {
  _FakeAuthUser_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsState_14 extends _i1.SmartFake
    implements _i10.SettingsState {
  _FakeSettingsState_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpeechService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechService extends _i1.Mock implements _i11.SpeechService {
  MockSpeechService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<String?> transcribeAudio(
    String? filePath, {
    String? language = 'en',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transcribeAudio,
              [filePath],
              {#language: language},
            ),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);
}

/// A class which mocks [AudioRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorder extends _i1.Mock implements _i13.AudioRecorder {
  MockAudioRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<void> start(_i2.RecordConfig? config, {required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#start, [config], {#path: path}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i12.Stream<_i14.Uint8List>> startStream(
    _i2.RecordConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startStream, [config]),
            returnValue: _i12.Future<_i12.Stream<_i14.Uint8List>>.value(
              _i12.Stream<_i14.Uint8List>.empty(),
            ),
          )
          as _i12.Future<_i12.Stream<_i14.Uint8List>>);

  @override
  _i12.Future<String?> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> isRecording() =>
      (super.noSuchMethod(
            Invocation.method(#isRecording, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> isPaused() =>
      (super.noSuchMethod(
            Invocation.method(#isPaused, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<List<_i2.InputDevice>> listInputDevices() =>
      (super.noSuchMethod(
            Invocation.method(#listInputDevices, []),
            returnValue: _i12.Future<List<_i2.InputDevice>>.value(
              <_i2.InputDevice>[],
            ),
          )
          as _i12.Future<List<_i2.InputDevice>>);

  @override
  _i12.Future<_i2.Amplitude> getAmplitude() =>
      (super.noSuchMethod(
            Invocation.method(#getAmplitude, []),
            returnValue: _i12.Future<_i2.Amplitude>.value(
              _FakeAmplitude_0(this, Invocation.method(#getAmplitude, [])),
            ),
          )
          as _i12.Future<_i2.Amplitude>);

  @override
  _i12.Future<bool> isEncoderSupported(_i2.AudioEncoder? encoder) =>
      (super.noSuchMethod(
            Invocation.method(#isEncoderSupported, [encoder]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Stream<_i2.RecordState> onStateChanged() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanged, []),
            returnValue: _i12.Stream<_i2.RecordState>.empty(),
          )
          as _i12.Stream<_i2.RecordState>);

  @override
  _i12.Stream<_i2.Amplitude> onAmplitudeChanged(Duration? interval) =>
      (super.noSuchMethod(
            Invocation.method(#onAmplitudeChanged, [interval]),
            returnValue: _i12.Stream<_i2.Amplitude>.empty(),
          )
          as _i12.Stream<_i2.Amplitude>);

  @override
  List<int> convertBytesToInt16(
    _i14.Uint8List? bytes, [
    dynamic endian = _i14.Endian.little,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#convertBytesToInt16, [bytes, endian]),
            returnValue: <int>[],
          )
          as List<int>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i15.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i16.PermissionStatus> getMicrophoneStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getMicrophoneStatus, []),
            returnValue: _i12.Future<_i16.PermissionStatus>.value(
              _i16.PermissionStatus.denied,
            ),
          )
          as _i12.Future<_i16.PermissionStatus>);

  @override
  _i12.Future<_i16.PermissionStatus> requestMicrophonePermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestMicrophonePermission, []),
            returnValue: _i12.Future<_i16.PermissionStatus>.value(
              _i16.PermissionStatus.denied,
            ),
          )
          as _i12.Future<_i16.PermissionStatus>);
}

/// A class which mocks [EntryPersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntryPersistenceService extends _i1.Mock
    implements _i17.EntryPersistenceService {
  MockEntryPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<_i18.Entry>> loadEntries() =>
      (super.noSuchMethod(
            Invocation.method(#loadEntries, []),
            returnValue: _i12.Future<List<_i18.Entry>>.value(<_i18.Entry>[]),
          )
          as _i12.Future<List<_i18.Entry>>);

  @override
  _i12.Future<void> saveEntries(List<_i18.Entry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#saveEntries, [entries]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<List<_i19.Category>> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i12.Future<List<_i19.Category>>.value(
              <_i19.Category>[],
            ),
          )
          as _i12.Future<List<_i19.Category>>);

  @override
  _i12.Future<void> saveCategories(List<_i19.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#saveCategories, [categories]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i20.AiService {
  MockAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<List<({String category, bool isTask, String textSegment})>>
  extractEntries(String? text, List<_i19.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#extractEntries, [text, categories]),
            returnValue:
                _i12.Future<
                  List<({String category, bool isTask, String textSegment})>
                >.value(
                  <({String category, bool isTask, String textSegment})>[],
                ),
          )
          as _i12.Future<
            List<({String category, bool isTask, String textSegment})>
          >);

  @override
  _i12.Future<(String, String?)> getChatResponse({
    required List<_i21.ChatMessage>? messages,
    DateTime? currentDate,
    bool? store = true,
    String? previousResponseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatResponse, [], {
              #messages: messages,
              #currentDate: currentDate,
              #store: store,
              #previousResponseId: previousResponseId,
            }),
            returnValue: _i12.Future<(String, String?)>.value((
              _i22.dummyValue<String>(
                this,
                Invocation.method(#getChatResponse, [], {
                  #messages: messages,
                  #currentDate: currentDate,
                  #store: store,
                  #previousResponseId: previousResponseId,
                }),
              ),
              null,
            )),
          )
          as _i12.Future<(String, String?)>);

  @override
  _i12.Stream<_i20.ChatStreamEvent> streamChatResponse({
    required List<_i21.ChatMessage>? messages,
    DateTime? currentDate,
    bool? store = true,
    String? previousResponseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamChatResponse, [], {
              #messages: messages,
              #currentDate: currentDate,
              #store: store,
              #previousResponseId: previousResponseId,
            }),
            returnValue: _i12.Stream<_i20.ChatStreamEvent>.empty(),
          )
          as _i12.Stream<_i20.ChatStreamEvent>);

  @override
  _i12.Future<_i3.ComprehensiveInsight> generateEntryInsights(
    String? entryText,
    String? entryId, {
    DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateEntryInsights,
              [entryText, entryId],
              {#currentDate: currentDate},
            ),
            returnValue: _i12.Future<_i3.ComprehensiveInsight>.value(
              _FakeComprehensiveInsight_1(
                this,
                Invocation.method(
                  #generateEntryInsights,
                  [entryText, entryId],
                  {#currentDate: currentDate},
                ),
              ),
            ),
          )
          as _i12.Future<_i3.ComprehensiveInsight>);

  @override
  _i12.Future<_i4.SimpleInsight> generateSimpleInsight(
    String? entryText,
    String? entryId, {
    DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateSimpleInsight,
              [entryText, entryId],
              {#currentDate: currentDate},
            ),
            returnValue: _i12.Future<_i4.SimpleInsight>.value(
              _FakeSimpleInsight_2(
                this,
                Invocation.method(
                  #generateSimpleInsight,
                  [entryText, entryId],
                  {#currentDate: currentDate},
                ),
              ),
            ),
          )
          as _i12.Future<_i4.SimpleInsight>);

  @override
  _i12.Future<
    ({
      String category,
      String imageDescription,
      String imageTitle,
      String insight,
      bool isTask,
    })
  >
  analyzeImage({
    required _i14.Uint8List? imageBytes,
    required List<_i19.Category>? categories,
    String? userNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImage, [], {
              #imageBytes: imageBytes,
              #categories: categories,
              #userNote: userNote,
            }),
            returnValue:
                _i12.Future<
                  ({
                    String category,
                    String imageDescription,
                    String imageTitle,
                    String insight,
                    bool isTask,
                  })
                >.value((
                  category: _i22.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  imageDescription: _i22.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  imageTitle: _i22.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  insight: _i22.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  isTask: false,
                )),
          )
          as _i12.Future<
            ({
              String category,
              String imageDescription,
              String imageTitle,
              String insight,
              bool isTask,
            })
          >);

  @override
  _i12.Future<List<String>> generatePromptSuggestions({
    required List<Map<String, dynamic>>? entries,
    required DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePromptSuggestions, [], {
              #entries: entries,
              #currentDate: currentDate,
            }),
            returnValue: _i12.Future<List<String>>.value(<String>[]),
          )
          as _i12.Future<List<String>>);
}

/// A class which mocks [AudioRecorderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorderService extends _i1.Mock
    implements _i23.AudioRecorderService {
  MockAudioRecorderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<void> start(_i2.RecordConfig? config, {required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#start, [config], {#path: path}),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<bool> isRecording() =>
      (super.noSuchMethod(
            Invocation.method(#isRecording, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Stream<_i2.RecordState> onStateChanged() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanged, []),
            returnValue: _i12.Stream<_i2.RecordState>.empty(),
          )
          as _i12.Stream<_i2.RecordState>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<String> generateRecordingPath() =>
      (super.noSuchMethod(
            Invocation.method(#generateRecordingPath, []),
            returnValue: _i12.Future<String>.value(
              _i22.dummyValue<String>(
                this,
                Invocation.method(#generateRecordingPath, []),
              ),
            ),
          )
          as _i12.Future<String>);
}

/// A class which mocks [VectorStoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVectorStoreService extends _i1.Mock
    implements _i24.VectorStoreService {
  MockVectorStoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> getMonthlyLogFileIds() =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyLogFileIds, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i12.Future<void> restoreFromSnapshot(
    String? vectorStoreId,
    Map<String, String>? monthlyLogFileIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromSnapshot, [
              vectorStoreId,
              monthlyLogFileIds,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> getOrCreateVectorStoreId() =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateVectorStoreId, []),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<void> synchronizeMonthlyLogFile(
    String? vectorStoreId,
    DateTime? date,
    String? formattedMonthlyLogContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#synchronizeMonthlyLogFile, [
              vectorStoreId,
              date,
              formattedMonthlyLogContent,
            ]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> performInitialBackfillIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#performInitialBackfillIfNeeded, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> cleanupDuplicateFiles() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupDuplicateFiles, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> clearLocalCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalCache, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> debugListVectorStoreFiles() =>
      (super.noSuchMethod(
            Invocation.method(#debugListVectorStoreFiles, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [ImageStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageStorageService extends _i1.Mock
    implements _i25.ImageStorageService {
  MockImageStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<String> saveImage(_i26.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#saveImage, [imageFile]),
            returnValue: _i12.Future<String>.value(
              _i22.dummyValue<String>(
                this,
                Invocation.method(#saveImage, [imageFile]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<String> saveImageBytes(
    _i14.Uint8List? bytes,
    String? extension,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveImageBytes, [bytes, extension]),
            returnValue: _i12.Future<String>.value(
              _i22.dummyValue<String>(
                this,
                Invocation.method(#saveImageBytes, [bytes, extension]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<void> deleteImage(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [relativePath]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i26.File?> getImage(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#getImage, [relativePath]),
            returnValue: _i12.Future<_i26.File?>.value(),
          )
          as _i12.Future<_i26.File?>);

  @override
  _i12.Future<String> getFullPath(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#getFullPath, [relativePath]),
            returnValue: _i12.Future<String>.value(
              _i22.dummyValue<String>(
                this,
                Invocation.method(#getFullPath, [relativePath]),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<_i14.Uint8List?> getImageBytes(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#getImageBytes, [relativePath]),
            returnValue: _i12.Future<_i14.Uint8List?>.value(),
          )
          as _i12.Future<_i14.Uint8List?>);
}

/// A class which mocks [FirestoreSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreSyncService extends _i1.Mock
    implements _i27.FirestoreSyncService {
  MockFirestoreSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onRemoteEntriesChanged(
    void Function(List<_i18.Entry>)? _onRemoteEntriesChanged,
  ) => super.noSuchMethod(
    Invocation.setter(#onRemoteEntriesChanged, _onRemoteEntriesChanged),
    returnValueForMissingStub: null,
  );

  @override
  set onRemoteCategoriesChanged(
    void Function(List<_i19.Category>)? _onRemoteCategoriesChanged,
  ) => super.noSuchMethod(
    Invocation.setter(#onRemoteCategoriesChanged, _onRemoteCategoriesChanged),
    returnValueForMissingStub: null,
  );

  @override
  void startListening(String? uid) => super.noSuchMethod(
    Invocation.method(#startListening, [uid]),
    returnValueForMissingStub: null,
  );

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<List<_i18.Entry>> fetchEntries(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEntries, [uid]),
            returnValue: _i12.Future<List<_i18.Entry>>.value(<_i18.Entry>[]),
          )
          as _i12.Future<List<_i18.Entry>>);

  @override
  _i12.Future<List<_i19.Category>> fetchCategories(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, [uid]),
            returnValue: _i12.Future<List<_i19.Category>>.value(
              <_i19.Category>[],
            ),
          )
          as _i12.Future<List<_i19.Category>>);

  @override
  _i12.Future<void> syncEntry(String? uid, _i18.Entry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#syncEntry, [uid, entry]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteEntry(String? uid, String? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [uid, entryId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncCategory(String? uid, _i19.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#syncCategory, [uid, category]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteCategory(String? uid, String? categoryName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [uid, categoryName]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncAllEntries(String? uid, List<_i18.Entry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllEntries, [uid, entries]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> syncAllCategories(
    String? uid,
    List<_i19.Category>? categories,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllCategories, [uid, categories]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  List<_i18.Entry> mergeEntries(
    List<_i18.Entry>? localEntries,
    List<_i18.Entry>? cloudEntries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mergeEntries, [localEntries, cloudEntries]),
            returnValue: <_i18.Entry>[],
          )
          as List<_i18.Entry>);

  @override
  List<_i19.Category> mergeCategories(
    List<_i19.Category>? localCategories,
    List<_i19.Category>? cloudCategories,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mergeCategories, [
              localCategories,
              cloudCategories,
            ]),
            returnValue: <_i19.Category>[],
          )
          as List<_i19.Category>);
}

/// A class which mocks [DeviceIdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceIdService extends _i1.Mock implements _i28.DeviceIdService {
  MockDeviceIdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<String> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i12.Future<String>.value(
              _i22.dummyValue<String>(
                this,
                Invocation.method(#getDeviceId, []),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<bool> hasDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#hasDeviceId, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}

/// A class which mocks [SnapshotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnapshotService extends _i1.Mock implements _i29.SnapshotService {
  MockSnapshotService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<void> createSnapshot({
    required String? deviceId,
    required List<_i18.Entry>? entries,
    required List<_i19.Category>? categories,
    String? vectorStoreId,
    Map<String, String>? monthlyLogFileIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSnapshot, [], {
              #deviceId: deviceId,
              #entries: entries,
              #categories: categories,
              #vectorStoreId: vectorStoreId,
              #monthlyLogFileIds: monthlyLogFileIds,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<_i29.Snapshot?> fetchSnapshot(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSnapshot, [deviceId]),
            returnValue: _i12.Future<_i29.Snapshot?>.value(),
          )
          as _i12.Future<_i29.Snapshot?>);

  @override
  _i12.Future<void> deleteSnapshot(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSnapshot, [deviceId]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> scheduleSnapshotDeletion(
    String? deviceId,
    Duration? delay,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleSnapshotDeletion, [deviceId, delay]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> hasValidSnapshot(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#hasValidSnapshot, [deviceId]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i5.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_3(this, Invocation.getter(#iOptions)),
          )
          as _i5.IOSOptions);

  @override
  _i5.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_4(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i5.AndroidOptions);

  @override
  _i5.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_5(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i5.LinuxOptions);

  @override
  _i5.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_6(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i5.WindowsOptions);

  @override
  _i5.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_7(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i5.WebOptions);

  @override
  _i5.AppleOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeAppleOptions_8(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i5.AppleOptions);

  @override
  Map<String, List<_i30.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
            Invocation.getter(#getListeners),
            returnValue: <String, List<_i30.ValueChanged<String?>>>{},
          )
          as Map<String, List<_i30.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i30.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i30.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> write({
    required String? key,
    required String? value,
    _i5.AppleOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.AppleOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<String?> read({
    required String? key,
    _i5.AppleOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.AppleOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i12.Future<String?>.value(),
          )
          as _i12.Future<String?>);

  @override
  _i12.Future<bool> containsKey({
    required String? key,
    _i5.AppleOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.AppleOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> delete({
    required String? key,
    _i5.AppleOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.AppleOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<Map<String, String>> readAll({
    _i5.AppleOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.AppleOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i12.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i12.Future<Map<String, String>>);

  @override
  _i12.Future<void> deleteAll({
    _i5.AppleOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.AppleOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i12.Future<bool?>.value(),
          )
          as _i12.Future<bool?>);
}

/// A class which mocks [IntentDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntentDetectionService extends _i1.Mock
    implements _i31.IntentDetectionService {
  MockIntentDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i6.IntentClassification> classifyIntent(String? userInput) =>
      (super.noSuchMethod(
            Invocation.method(#classifyIntent, [userInput]),
            returnValue: _i12.Future<_i6.IntentClassification>.value(
              _FakeIntentClassification_9(
                this,
                Invocation.method(#classifyIntent, [userInput]),
              ),
            ),
          )
          as _i12.Future<_i6.IntentClassification>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i32.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i12.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i7.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Future<_i7.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i12.Future<_i7.Response>.value(
              _FakeResponse_10(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i12.Future<_i7.Response>);

  @override
  _i12.Future<_i7.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i12.Future<_i7.Response>.value(
              _FakeResponse_10(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i12.Future<_i7.Response>);

  @override
  _i12.Future<_i7.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i12.Future<_i7.Response>.value(
              _FakeResponse_10(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i12.Future<_i7.Response>);

  @override
  _i12.Future<_i7.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i12.Future<_i7.Response>.value(
              _FakeResponse_10(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i12.Future<_i7.Response>);

  @override
  _i12.Future<_i7.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i12.Future<_i7.Response>.value(
              _FakeResponse_10(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i12.Future<_i7.Response>);

  @override
  _i12.Future<_i7.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i33.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i12.Future<_i7.Response>.value(
              _FakeResponse_10(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i12.Future<_i7.Response>);

  @override
  _i12.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i12.Future<String>.value(
              _i22.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i12.Future<String>);

  @override
  _i12.Future<_i14.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i12.Future<_i14.Uint8List>.value(_i14.Uint8List(0)),
          )
          as _i12.Future<_i14.Uint8List>);

  @override
  _i12.Future<_i7.StreamedResponse> send(_i7.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i12.Future<_i7.StreamedResponse>.value(
              _FakeStreamedResponse_11(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i12.Future<_i7.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChatCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatCubit extends _i1.Mock implements _i8.ChatCubit {
  MockChatCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.ChatState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeChatState_12(this, Invocation.getter(#state)),
          )
          as _i8.ChatState);

  @override
  _i12.Stream<_i8.ChatState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i8.ChatState>.empty(),
          )
          as _i12.Stream<_i8.ChatState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addUserMessage(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addUserMessage, [text]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> addUserMessageStreaming(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addUserMessageStreaming, [text]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void startChatWithQuery(String? queryText) => super.noSuchMethod(
    Invocation.method(#startChatWithQuery, [queryText]),
    returnValueForMissingStub: null,
  );

  @override
  void loadDummyMessages() => super.noSuchMethod(
    Invocation.method(#loadDummyMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.ChatState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i34.Change<_i8.ChatState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i9.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.Stream<_i9.AuthUser?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i12.Stream<_i9.AuthUser?>.empty(),
          )
          as _i12.Stream<_i9.AuthUser?>);

  @override
  _i12.Future<_i9.AuthUser> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i12.Future<_i9.AuthUser>.value(
              _FakeAuthUser_13(this, Invocation.method(#signInWithGoogle, [])),
            ),
          )
          as _i12.Future<_i9.AuthUser>);

  @override
  _i12.Future<_i9.AuthUser> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i12.Future<_i9.AuthUser>.value(
              _FakeAuthUser_13(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i12.Future<_i9.AuthUser>);

  @override
  _i12.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);
}

/// A class which mocks [SettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsCubit extends _i1.Mock implements _i10.SettingsCubit {
  MockSettingsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.SettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSettingsState_14(this, Invocation.getter(#state)),
          )
          as _i10.SettingsState);

  @override
  _i12.Stream<_i10.SettingsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i12.Stream<_i10.SettingsState>.empty(),
          )
          as _i12.Stream<_i10.SettingsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i12.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> confirmRecovery() =>
      (super.noSuchMethod(
            Invocation.method(#confirmRecovery, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void dismissRecovery() => super.noSuchMethod(
    Invocation.method(#dismissRecovery, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> checkForManualRecovery() =>
      (super.noSuchMethod(
            Invocation.method(#checkForManualRecovery, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void emit(_i10.SettingsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i34.Change<_i10.SettingsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
