// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i16;
import 'dart:convert' as _i38;
import 'dart:io' as _i30;
import 'dart:typed_data' as _i18;
import 'dart:ui' as _i41;

import 'package:firebase_core/firebase_core.dart' as _i13;
import 'package:firebase_storage/firebase_storage.dart' as _i14;
import 'package:flutter/foundation.dart' as _i35;
import 'package:flutter_bloc/flutter_bloc.dart' as _i39;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:http/http.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;
import 'package:myapp/chat/cubit/chat_cubit.dart' as _i9;
import 'package:myapp/chat/model/chat_message.dart' as _i25;
import 'package:myapp/dashboard_v2/model/insight.dart' as _i3;
import 'package:myapp/dashboard_v2/model/simple_insight.dart' as _i4;
import 'package:myapp/entry/category.dart' as _i23;
import 'package:myapp/entry/entry.dart' as _i22;
import 'package:myapp/entry/repository/entry_repository.dart' as _i40;
import 'package:myapp/intent_detection/models/models.dart' as _i7;
import 'package:myapp/intent_detection/services/intent_detection_service.dart'
    as _i36;
import 'package:myapp/onboarding/cubit/onboarding_cubit.dart' as _i12;
import 'package:myapp/services/ai_service.dart' as _i24;
import 'package:myapp/services/anonymous_auth_service.dart' as _i5;
import 'package:myapp/services/audio_recorder_service.dart' as _i27;
import 'package:myapp/services/device_id_service.dart' as _i33;
import 'package:myapp/services/entry_persistence_service.dart' as _i21;
import 'package:myapp/services/firestore_sync_service.dart' as _i32;
import 'package:myapp/services/image_storage_service.dart' as _i29;
import 'package:myapp/services/image_storage_sync_service.dart' as _i31;
import 'package:myapp/services/permission_service.dart' as _i19;
import 'package:myapp/services/snapshot_service.dart' as _i34;
import 'package:myapp/services/vector_store_service.dart' as _i28;
import 'package:myapp/settings/cubit/settings_cubit.dart' as _i11;
import 'package:myapp/settings/services/auth_service.dart' as _i10;
import 'package:myapp/speech_service.dart' as _i15;
import 'package:permission_handler/permission_handler.dart' as _i20;
import 'package:record/record.dart' as _i17;
import 'package:record_platform_interface/record_platform_interface.dart'
    as _i2;
import 'package:shared_preferences/shared_preferences.dart' as _i37;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAmplitude_0 extends _i1.SmartFake implements _i2.Amplitude {
  _FakeAmplitude_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComprehensiveInsight_1 extends _i1.SmartFake
    implements _i3.ComprehensiveInsight {
  _FakeComprehensiveInsight_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleInsight_2 extends _i1.SmartFake implements _i4.SimpleInsight {
  _FakeSimpleInsight_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnonymousAuthResult_3 extends _i1.SmartFake
    implements _i5.AnonymousAuthResult {
  _FakeAnonymousAuthResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_4 extends _i1.SmartFake implements _i6.IOSOptions {
  _FakeIOSOptions_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_5 extends _i1.SmartFake
    implements _i6.AndroidOptions {
  _FakeAndroidOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_6 extends _i1.SmartFake implements _i6.LinuxOptions {
  _FakeLinuxOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_7 extends _i1.SmartFake
    implements _i6.WindowsOptions {
  _FakeWindowsOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_8 extends _i1.SmartFake implements _i6.WebOptions {
  _FakeWebOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppleOptions_9 extends _i1.SmartFake implements _i6.AppleOptions {
  _FakeAppleOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIntentClassification_10 extends _i1.SmartFake
    implements _i7.IntentClassification {
  _FakeIntentClassification_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_11 extends _i1.SmartFake implements _i8.Response {
  _FakeResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_12 extends _i1.SmartFake
    implements _i8.StreamedResponse {
  _FakeStreamedResponse_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatState_13 extends _i1.SmartFake implements _i9.ChatState {
  _FakeChatState_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthUser_14 extends _i1.SmartFake implements _i10.AuthUser {
  _FakeAuthUser_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettingsState_15 extends _i1.SmartFake
    implements _i11.SettingsState {
  _FakeSettingsState_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOnboardingState_16 extends _i1.SmartFake
    implements _i12.OnboardingState {
  _FakeOnboardingState_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_17 extends _i1.SmartFake implements _i13.FirebaseApp {
  _FakeFirebaseApp_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDuration_18 extends _i1.SmartFake implements Duration {
  _FakeDuration_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReference_19 extends _i1.SmartFake implements _i14.Reference {
  _FakeReference_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseStorage_20 extends _i1.SmartFake
    implements _i14.FirebaseStorage {
  _FakeFirebaseStorage_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFullMetadata_21 extends _i1.SmartFake implements _i14.FullMetadata {
  _FakeFullMetadata_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeListResult_22 extends _i1.SmartFake implements _i14.ListResult {
  _FakeListResult_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUploadTask_23 extends _i1.SmartFake implements _i14.UploadTask {
  _FakeUploadTask_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDownloadTask_24 extends _i1.SmartFake implements _i14.DownloadTask {
  _FakeDownloadTask_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpeechService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpeechService extends _i1.Mock implements _i15.SpeechService {
  MockSpeechService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<String?> transcribeAudio(
    String? filePath, {
    String? language = 'en',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transcribeAudio,
              [filePath],
              {#language: language},
            ),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);
}

/// A class which mocks [AudioRecorder].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorder extends _i1.Mock implements _i17.AudioRecorder {
  MockAudioRecorder() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<void> start(_i2.RecordConfig? config, {required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#start, [config], {#path: path}),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i16.Stream<_i18.Uint8List>> startStream(
    _i2.RecordConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startStream, [config]),
            returnValue: _i16.Future<_i16.Stream<_i18.Uint8List>>.value(
              _i16.Stream<_i18.Uint8List>.empty(),
            ),
          )
          as _i16.Future<_i16.Stream<_i18.Uint8List>>);

  @override
  _i16.Future<String?> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  _i16.Future<void> cancel() =>
      (super.noSuchMethod(
            Invocation.method(#cancel, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool> isRecording() =>
      (super.noSuchMethod(
            Invocation.method(#isRecording, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> isPaused() =>
      (super.noSuchMethod(
            Invocation.method(#isPaused, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<List<_i2.InputDevice>> listInputDevices() =>
      (super.noSuchMethod(
            Invocation.method(#listInputDevices, []),
            returnValue: _i16.Future<List<_i2.InputDevice>>.value(
              <_i2.InputDevice>[],
            ),
          )
          as _i16.Future<List<_i2.InputDevice>>);

  @override
  _i16.Future<_i2.Amplitude> getAmplitude() =>
      (super.noSuchMethod(
            Invocation.method(#getAmplitude, []),
            returnValue: _i16.Future<_i2.Amplitude>.value(
              _FakeAmplitude_0(this, Invocation.method(#getAmplitude, [])),
            ),
          )
          as _i16.Future<_i2.Amplitude>);

  @override
  _i16.Future<bool> isEncoderSupported(_i2.AudioEncoder? encoder) =>
      (super.noSuchMethod(
            Invocation.method(#isEncoderSupported, [encoder]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Stream<_i2.RecordState> onStateChanged() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanged, []),
            returnValue: _i16.Stream<_i2.RecordState>.empty(),
          )
          as _i16.Stream<_i2.RecordState>);

  @override
  _i16.Stream<_i2.Amplitude> onAmplitudeChanged(Duration? interval) =>
      (super.noSuchMethod(
            Invocation.method(#onAmplitudeChanged, [interval]),
            returnValue: _i16.Stream<_i2.Amplitude>.empty(),
          )
          as _i16.Stream<_i2.Amplitude>);

  @override
  List<int> convertBytesToInt16(
    _i18.Uint8List? bytes, [
    dynamic endian = _i18.Endian.little,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#convertBytesToInt16, [bytes, endian]),
            returnValue: <int>[],
          )
          as List<int>);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i19.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i20.PermissionStatus> getMicrophoneStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getMicrophoneStatus, []),
            returnValue: _i16.Future<_i20.PermissionStatus>.value(
              _i20.PermissionStatus.denied,
            ),
          )
          as _i16.Future<_i20.PermissionStatus>);

  @override
  _i16.Future<_i20.PermissionStatus> requestMicrophonePermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestMicrophonePermission, []),
            returnValue: _i16.Future<_i20.PermissionStatus>.value(
              _i20.PermissionStatus.denied,
            ),
          )
          as _i16.Future<_i20.PermissionStatus>);
}

/// A class which mocks [EntryPersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntryPersistenceService extends _i1.Mock
    implements _i21.EntryPersistenceService {
  MockEntryPersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<List<_i22.Entry>> loadEntries() =>
      (super.noSuchMethod(
            Invocation.method(#loadEntries, []),
            returnValue: _i16.Future<List<_i22.Entry>>.value(<_i22.Entry>[]),
          )
          as _i16.Future<List<_i22.Entry>>);

  @override
  _i16.Future<void> saveEntries(List<_i22.Entry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#saveEntries, [entries]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<List<_i23.Category>> loadCategories() =>
      (super.noSuchMethod(
            Invocation.method(#loadCategories, []),
            returnValue: _i16.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i16.Future<List<_i23.Category>>);

  @override
  _i16.Future<void> saveCategories(List<_i23.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#saveCategories, [categories]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> clearAllData() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllData, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [AiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiService extends _i1.Mock implements _i24.AiService {
  MockAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<List<({String category, bool isTask, String textSegment})>>
  extractEntries(String? text, List<_i23.Category>? categories) =>
      (super.noSuchMethod(
            Invocation.method(#extractEntries, [text, categories]),
            returnValue:
                _i16.Future<
                  List<({String category, bool isTask, String textSegment})>
                >.value(
                  <({String category, bool isTask, String textSegment})>[],
                ),
          )
          as _i16.Future<
            List<({String category, bool isTask, String textSegment})>
          >);

  @override
  _i16.Future<(String, String?)> getChatResponse({
    required List<_i25.ChatMessage>? messages,
    DateTime? currentDate,
    bool? store = true,
    String? previousResponseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatResponse, [], {
              #messages: messages,
              #currentDate: currentDate,
              #store: store,
              #previousResponseId: previousResponseId,
            }),
            returnValue: _i16.Future<(String, String?)>.value((
              _i26.dummyValue<String>(
                this,
                Invocation.method(#getChatResponse, [], {
                  #messages: messages,
                  #currentDate: currentDate,
                  #store: store,
                  #previousResponseId: previousResponseId,
                }),
              ),
              null,
            )),
          )
          as _i16.Future<(String, String?)>);

  @override
  _i16.Stream<_i24.ChatStreamEvent> streamChatResponse({
    required List<_i25.ChatMessage>? messages,
    DateTime? currentDate,
    bool? store = true,
    String? previousResponseId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#streamChatResponse, [], {
              #messages: messages,
              #currentDate: currentDate,
              #store: store,
              #previousResponseId: previousResponseId,
            }),
            returnValue: _i16.Stream<_i24.ChatStreamEvent>.empty(),
          )
          as _i16.Stream<_i24.ChatStreamEvent>);

  @override
  _i16.Future<_i3.ComprehensiveInsight> generateEntryInsights(
    String? entryText,
    String? entryId, {
    DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateEntryInsights,
              [entryText, entryId],
              {#currentDate: currentDate},
            ),
            returnValue: _i16.Future<_i3.ComprehensiveInsight>.value(
              _FakeComprehensiveInsight_1(
                this,
                Invocation.method(
                  #generateEntryInsights,
                  [entryText, entryId],
                  {#currentDate: currentDate},
                ),
              ),
            ),
          )
          as _i16.Future<_i3.ComprehensiveInsight>);

  @override
  _i16.Future<_i4.SimpleInsight> generateSimpleInsight(
    String? entryText,
    String? entryId, {
    DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateSimpleInsight,
              [entryText, entryId],
              {#currentDate: currentDate},
            ),
            returnValue: _i16.Future<_i4.SimpleInsight>.value(
              _FakeSimpleInsight_2(
                this,
                Invocation.method(
                  #generateSimpleInsight,
                  [entryText, entryId],
                  {#currentDate: currentDate},
                ),
              ),
            ),
          )
          as _i16.Future<_i4.SimpleInsight>);

  @override
  _i16.Future<
    ({
      String category,
      String imageDescription,
      String imageTitle,
      String insight,
      bool isTask,
    })
  >
  analyzeImage({
    required _i18.Uint8List? imageBytes,
    required List<_i23.Category>? categories,
    String? userNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImage, [], {
              #imageBytes: imageBytes,
              #categories: categories,
              #userNote: userNote,
            }),
            returnValue:
                _i16.Future<
                  ({
                    String category,
                    String imageDescription,
                    String imageTitle,
                    String insight,
                    bool isTask,
                  })
                >.value((
                  category: _i26.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  imageDescription: _i26.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  imageTitle: _i26.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  insight: _i26.dummyValue<String>(
                    this,
                    Invocation.method(#analyzeImage, [], {
                      #imageBytes: imageBytes,
                      #categories: categories,
                      #userNote: userNote,
                    }),
                  ),
                  isTask: false,
                )),
          )
          as _i16.Future<
            ({
              String category,
              String imageDescription,
              String imageTitle,
              String insight,
              bool isTask,
            })
          >);

  @override
  _i16.Future<List<String>> generatePromptSuggestions({
    required List<Map<String, dynamic>>? entries,
    required DateTime? currentDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generatePromptSuggestions, [], {
              #entries: entries,
              #currentDate: currentDate,
            }),
            returnValue: _i16.Future<List<String>>.value(<String>[]),
          )
          as _i16.Future<List<String>>);
}

/// A class which mocks [AnonymousAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnonymousAuthService extends _i1.Mock
    implements _i5.AnonymousAuthService {
  MockAnonymousAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool hasAuthentication() =>
      (super.noSuchMethod(
            Invocation.method(#hasAuthentication, []),
            returnValue: false,
          )
          as bool);

  @override
  _i16.Future<_i5.AnonymousAuthResult> ensureAnonymousAuth() =>
      (super.noSuchMethod(
            Invocation.method(#ensureAnonymousAuth, []),
            returnValue: _i16.Future<_i5.AnonymousAuthResult>.value(
              _FakeAnonymousAuthResult_3(
                this,
                Invocation.method(#ensureAnonymousAuth, []),
              ),
            ),
          )
          as _i16.Future<_i5.AnonymousAuthResult>);
}

/// A class which mocks [AudioRecorderService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioRecorderService extends _i1.Mock
    implements _i27.AudioRecorderService {
  MockAudioRecorderService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<void> start(_i2.RecordConfig? config, {required String? path}) =>
      (super.noSuchMethod(
            Invocation.method(#start, [config], {#path: path}),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<String?> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  _i16.Future<bool> isRecording() =>
      (super.noSuchMethod(
            Invocation.method(#isRecording, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Stream<_i2.RecordState> onStateChanged() =>
      (super.noSuchMethod(
            Invocation.method(#onStateChanged, []),
            returnValue: _i16.Stream<_i2.RecordState>.empty(),
          )
          as _i16.Stream<_i2.RecordState>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<String> generateRecordingPath() =>
      (super.noSuchMethod(
            Invocation.method(#generateRecordingPath, []),
            returnValue: _i16.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#generateRecordingPath, []),
              ),
            ),
          )
          as _i16.Future<String>);
}

/// A class which mocks [VectorStoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVectorStoreService extends _i1.Mock
    implements _i28.VectorStoreService {
  MockVectorStoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> getMonthlyLogFileIds() =>
      (super.noSuchMethod(
            Invocation.method(#getMonthlyLogFileIds, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i16.Future<void> restoreFromSnapshot(
    String? vectorStoreId,
    Map<String, String>? monthlyLogFileIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromSnapshot, [
              vectorStoreId,
              monthlyLogFileIds,
            ]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<String?> getOrCreateVectorStoreId() =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateVectorStoreId, []),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  _i16.Future<void> synchronizeMonthlyLogFile(
    String? vectorStoreId,
    DateTime? date,
    String? formattedMonthlyLogContent,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#synchronizeMonthlyLogFile, [
              vectorStoreId,
              date,
              formattedMonthlyLogContent,
            ]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> performInitialBackfillIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#performInitialBackfillIfNeeded, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> cleanupDuplicateFiles() =>
      (super.noSuchMethod(
            Invocation.method(#cleanupDuplicateFiles, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> clearLocalCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearLocalCache, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> debugListVectorStoreFiles() =>
      (super.noSuchMethod(
            Invocation.method(#debugListVectorStoreFiles, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [ImageStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageStorageService extends _i1.Mock
    implements _i29.ImageStorageService {
  MockImageStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<String> saveImage(_i30.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#saveImage, [imageFile]),
            returnValue: _i16.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#saveImage, [imageFile]),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<String> saveImageBytes(
    _i18.Uint8List? bytes,
    String? extension,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveImageBytes, [bytes, extension]),
            returnValue: _i16.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#saveImageBytes, [bytes, extension]),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<void> deleteImage(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [relativePath]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i30.File?> getImage(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#getImage, [relativePath]),
            returnValue: _i16.Future<_i30.File?>.value(),
          )
          as _i16.Future<_i30.File?>);

  @override
  _i16.Future<String> getFullPath(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#getFullPath, [relativePath]),
            returnValue: _i16.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#getFullPath, [relativePath]),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<_i18.Uint8List?> getImageBytes(String? relativePath) =>
      (super.noSuchMethod(
            Invocation.method(#getImageBytes, [relativePath]),
            returnValue: _i16.Future<_i18.Uint8List?>.value(),
          )
          as _i16.Future<_i18.Uint8List?>);
}

/// A class which mocks [ImageStorageSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageStorageSyncService extends _i1.Mock
    implements _i31.ImageStorageSyncService {
  MockImageStorageSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<String?> uploadImage(_i30.File? imageFile, String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [imageFile, uuid]),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  _i16.Future<bool> downloadImage(String? cloudPath, String? localPath) =>
      (super.noSuchMethod(
            Invocation.method(#downloadImage, [cloudPath, localPath]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> deleteImage(String? cloudPath) =>
      (super.noSuchMethod(
            Invocation.method(#deleteImage, [cloudPath]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<String?> getDownloadUrl(String? cloudPath) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadUrl, [cloudPath]),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  void clearUrlCache() => super.noSuchMethod(
    Invocation.method(#clearUrlCache, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirestoreSyncService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreSyncService extends _i1.Mock
    implements _i32.FirestoreSyncService {
  MockFirestoreSyncService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasMoreEntries =>
      (super.noSuchMethod(
            Invocation.getter(#hasMoreEntries),
            returnValue: false,
          )
          as bool);

  @override
  set onRemoteCategoriesChanged(
    void Function(List<_i23.Category>)? _onRemoteCategoriesChanged,
  ) => super.noSuchMethod(
    Invocation.setter(#onRemoteCategoriesChanged, _onRemoteCategoriesChanged),
    returnValueForMissingStub: null,
  );

  @override
  void startListening(String? uid) => super.noSuchMethod(
    Invocation.method(#startListening, [uid]),
    returnValueForMissingStub: null,
  );

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  void resetPagination() => super.noSuchMethod(
    Invocation.method(#resetPagination, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<List<_i22.Entry>> fetchEntries(String? uid, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchEntries, [uid], {#limit: limit}),
            returnValue: _i16.Future<List<_i22.Entry>>.value(<_i22.Entry>[]),
          )
          as _i16.Future<List<_i22.Entry>>);

  @override
  _i16.Future<List<_i22.Entry>> fetchMoreEntries(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMoreEntries, [uid]),
            returnValue: _i16.Future<List<_i22.Entry>>.value(<_i22.Entry>[]),
          )
          as _i16.Future<List<_i22.Entry>>);

  @override
  _i16.Future<List<_i23.Category>> fetchCategories(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCategories, [uid]),
            returnValue: _i16.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i16.Future<List<_i23.Category>>);

  @override
  _i16.Future<void> syncEntry(String? uid, _i22.Entry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#syncEntry, [uid, entry]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> deleteEntry(String? uid, String? entryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [uid, entryId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> syncCategory(String? uid, _i23.Category? category) =>
      (super.noSuchMethod(
            Invocation.method(#syncCategory, [uid, category]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> deleteCategory(String? uid, String? categoryName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [uid, categoryName]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> syncAllEntries(String? uid, List<_i22.Entry>? entries) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllEntries, [uid, entries]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> syncAllCategories(
    String? uid,
    List<_i23.Category>? categories,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#syncAllCategories, [uid, categories]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  List<_i22.Entry> mergeEntries(
    List<_i22.Entry>? localEntries,
    List<_i22.Entry>? cloudEntries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mergeEntries, [localEntries, cloudEntries]),
            returnValue: <_i22.Entry>[],
          )
          as List<_i22.Entry>);

  @override
  List<_i23.Category> mergeCategories(
    List<_i23.Category>? localCategories,
    List<_i23.Category>? cloudCategories,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#mergeCategories, [
              localCategories,
              cloudCategories,
            ]),
            returnValue: <_i23.Category>[],
          )
          as List<_i23.Category>);
}

/// A class which mocks [DeviceIdService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceIdService extends _i1.Mock implements _i33.DeviceIdService {
  MockDeviceIdService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<String> getDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#getDeviceId, []),
            returnValue: _i16.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#getDeviceId, []),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<bool> hasDeviceId() =>
      (super.noSuchMethod(
            Invocation.method(#hasDeviceId, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [SnapshotService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnapshotService extends _i1.Mock implements _i34.SnapshotService {
  MockSnapshotService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<void> createSnapshot({
    required String? deviceId,
    required List<_i22.Entry>? entries,
    required List<_i23.Category>? categories,
    String? vectorStoreId,
    Map<String, String>? monthlyLogFileIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSnapshot, [], {
              #deviceId: deviceId,
              #entries: entries,
              #categories: categories,
              #vectorStoreId: vectorStoreId,
              #monthlyLogFileIds: monthlyLogFileIds,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<_i34.Snapshot?> fetchSnapshot(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSnapshot, [deviceId]),
            returnValue: _i16.Future<_i34.Snapshot?>.value(),
          )
          as _i16.Future<_i34.Snapshot?>);

  @override
  _i16.Future<void> deleteSnapshot(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSnapshot, [deviceId]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> scheduleSnapshotDeletion(
    String? deviceId,
    Duration? delay,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#scheduleSnapshotDeletion, [deviceId, delay]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool> hasValidSnapshot(String? deviceId) =>
      (super.noSuchMethod(
            Invocation.method(#hasValidSnapshot, [deviceId]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i6.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_4(this, Invocation.getter(#iOptions)),
          )
          as _i6.IOSOptions);

  @override
  _i6.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_5(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i6.AndroidOptions);

  @override
  _i6.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_6(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i6.LinuxOptions);

  @override
  _i6.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_7(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i6.WindowsOptions);

  @override
  _i6.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_8(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i6.WebOptions);

  @override
  _i6.AppleOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeAppleOptions_9(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i6.AppleOptions);

  @override
  Map<String, List<_i35.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
            Invocation.getter(#getListeners),
            returnValue: <String, List<_i35.ValueChanged<String?>>>{},
          )
          as Map<String, List<_i35.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i35.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i35.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> write({
    required String? key,
    required String? value,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<String?> read({
    required String? key,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  _i16.Future<bool> containsKey({
    required String? key,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<void> delete({
    required String? key,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<Map<String, String>> readAll({
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i16.Future<Map<String, String>>);

  @override
  _i16.Future<void> deleteAll({
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i16.Future<bool?>.value(),
          )
          as _i16.Future<bool?>);
}

/// A class which mocks [IntentDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIntentDetectionService extends _i1.Mock
    implements _i36.IntentDetectionService {
  MockIntentDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i7.IntentClassification> classifyIntent(String? userInput) =>
      (super.noSuchMethod(
            Invocation.method(#classifyIntent, [userInput]),
            returnValue: _i16.Future<_i7.IntentClassification>.value(
              _FakeIntentClassification_10(
                this,
                Invocation.method(#classifyIntent, [userInput]),
              ),
            ),
          )
          as _i16.Future<_i7.IntentClassification>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i37.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i16.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i8.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Future<_i8.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i16.Future<_i8.Response>.value(
              _FakeResponse_11(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<_i8.Response>);

  @override
  _i16.Future<_i8.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i16.Future<_i8.Response>.value(
              _FakeResponse_11(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<_i8.Response>);

  @override
  _i16.Future<_i8.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i38.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i8.Response>.value(
              _FakeResponse_11(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i8.Response>);

  @override
  _i16.Future<_i8.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i38.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i8.Response>.value(
              _FakeResponse_11(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i8.Response>);

  @override
  _i16.Future<_i8.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i38.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i8.Response>.value(
              _FakeResponse_11(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i8.Response>);

  @override
  _i16.Future<_i8.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i38.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i16.Future<_i8.Response>.value(
              _FakeResponse_11(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i16.Future<_i8.Response>);

  @override
  _i16.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i16.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<_i18.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i16.Future<_i18.Uint8List>.value(_i18.Uint8List(0)),
          )
          as _i16.Future<_i18.Uint8List>);

  @override
  _i16.Future<_i8.StreamedResponse> send(_i8.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i16.Future<_i8.StreamedResponse>.value(
              _FakeStreamedResponse_12(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i16.Future<_i8.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ChatCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatCubit extends _i1.Mock implements _i9.ChatCubit {
  MockChatCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.ChatState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeChatState_13(this, Invocation.getter(#state)),
          )
          as _i9.ChatState);

  @override
  _i16.Stream<_i9.ChatState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i9.ChatState>.empty(),
          )
          as _i16.Stream<_i9.ChatState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> addUserMessage(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addUserMessage, [text]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> addUserMessageStreaming(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#addUserMessageStreaming, [text]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void startChatWithQuery(String? queryText) => super.noSuchMethod(
    Invocation.method(#startChatWithQuery, [queryText]),
    returnValueForMissingStub: null,
  );

  @override
  void loadDummyMessages() => super.noSuchMethod(
    Invocation.method(#loadDummyMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i9.ChatState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i39.Change<_i9.ChatState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Stream<_i10.AuthUser?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i16.Stream<_i10.AuthUser?>.empty(),
          )
          as _i16.Stream<_i10.AuthUser?>);

  @override
  _i16.Future<_i10.AuthUser> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i16.Future<_i10.AuthUser>.value(
              _FakeAuthUser_14(this, Invocation.method(#signInWithGoogle, [])),
            ),
          )
          as _i16.Future<_i10.AuthUser>);

  @override
  _i16.Future<_i10.AuthUser> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i16.Future<_i10.AuthUser>.value(
              _FakeAuthUser_14(this, Invocation.method(#signInWithApple, [])),
            ),
          )
          as _i16.Future<_i10.AuthUser>);

  @override
  _i16.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [SettingsCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsCubit extends _i1.Mock implements _i11.SettingsCubit {
  MockSettingsCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.SettingsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeSettingsState_15(this, Invocation.getter(#state)),
          )
          as _i11.SettingsState);

  @override
  _i16.Stream<_i11.SettingsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i11.SettingsState>.empty(),
          )
          as _i16.Stream<_i11.SettingsState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i16.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> confirmRecovery() =>
      (super.noSuchMethod(
            Invocation.method(#confirmRecovery, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void dismissRecovery() => super.noSuchMethod(
    Invocation.method(#dismissRecovery, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> checkForManualRecovery() =>
      (super.noSuchMethod(
            Invocation.method(#checkForManualRecovery, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void emit(_i11.SettingsState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i39.Change<_i11.SettingsState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OnboardingCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnboardingCubit extends _i1.Mock implements _i12.OnboardingCubit {
  MockOnboardingCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i12.OnboardingState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOnboardingState_16(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i12.OnboardingState);

  @override
  _i16.Stream<_i12.OnboardingState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i16.Stream<_i12.OnboardingState>.empty(),
          )
          as _i16.Stream<_i12.OnboardingState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool isOnboardingCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#isOnboardingCompleted, []),
            returnValue: false,
          )
          as bool);

  @override
  _i16.Future<void> nextStep() =>
      (super.noSuchMethod(
            Invocation.method(#nextStep, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> previousStep() =>
      (super.noSuchMethod(
            Invocation.method(#previousStep, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void toggleCategorySelection(String? category) => super.noSuchMethod(
    Invocation.method(#toggleCategorySelection, [category]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> addCustomCategory(String? categoryName) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomCategory, [categoryName]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> completeOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#completeOnboarding, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearAuthError() => super.noSuchMethod(
    Invocation.method(#clearAuthError, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> retryConnection() =>
      (super.noSuchMethod(
            Invocation.method(#retryConnection, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> resetOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#resetOnboarding, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  void emit(_i12.OnboardingState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i39.Change<_i12.OnboardingState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [EntryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntryRepository extends _i1.Mock implements _i40.EntryRepository {
  MockEntryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i16.Stream<List<_i22.Entry>> get entriesStream =>
      (super.noSuchMethod(
            Invocation.getter(#entriesStream),
            returnValue: _i16.Stream<List<_i22.Entry>>.empty(),
          )
          as _i16.Stream<List<_i22.Entry>>);

  @override
  _i16.Stream<List<_i23.Category>> get categoriesStream =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesStream),
            returnValue: _i16.Stream<List<_i23.Category>>.empty(),
          )
          as _i16.Stream<List<_i23.Category>>);

  @override
  List<_i22.Entry> get currentEntries =>
      (super.noSuchMethod(
            Invocation.getter(#currentEntries),
            returnValue: <_i22.Entry>[],
          )
          as List<_i22.Entry>);

  @override
  List<_i23.Category> get currentCategories =>
      (super.noSuchMethod(
            Invocation.getter(#currentCategories),
            returnValue: <_i23.Category>[],
          )
          as List<_i23.Category>);

  @override
  List<_i23.Category> get activeCategories =>
      (super.noSuchMethod(
            Invocation.getter(#activeCategories),
            returnValue: <_i23.Category>[],
          )
          as List<_i23.Category>);

  @override
  bool get hasMoreFirestoreEntries =>
      (super.noSuchMethod(
            Invocation.getter(#hasMoreFirestoreEntries),
            returnValue: false,
          )
          as bool);

  @override
  _i16.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<({List<_i22.Entry> entries, int splitCount})> addEntry(
    String? text,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addEntry, [text]),
            returnValue:
                _i16.Future<({List<_i22.Entry> entries, int splitCount})>.value(
                  (entries: <_i22.Entry>[], splitCount: 0),
                ),
          )
          as _i16.Future<({List<_i22.Entry> entries, int splitCount})>);

  @override
  void retryPendingEntries() => super.noSuchMethod(
    Invocation.method(#retryPendingEntries, []),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<List<_i22.Entry>> addEntryObject(_i22.Entry? entryToAdd) =>
      (super.noSuchMethod(
            Invocation.method(#addEntryObject, [entryToAdd]),
            returnValue: _i16.Future<List<_i22.Entry>>.value(<_i22.Entry>[]),
          )
          as _i16.Future<List<_i22.Entry>>);

  @override
  _i16.Future<List<_i22.Entry>> addEntryObjects(
    List<_i22.Entry>? entriesToAdd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addEntryObjects, [entriesToAdd]),
            returnValue: _i16.Future<List<_i22.Entry>>.value(<_i22.Entry>[]),
          )
          as _i16.Future<List<_i22.Entry>>);

  @override
  _i16.Future<List<_i23.Category>> addCategoryObjects(
    List<_i23.Category>? categoriesToAdd,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addCategoryObjects, [categoriesToAdd]),
            returnValue: _i16.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i16.Future<List<_i23.Category>>);

  @override
  _i16.Future<({_i22.Entry? addedEntry, List<_i22.Entry> entries})>
  addImageEntry({required _i18.Uint8List? imageBytes, String? userNote}) =>
      (super.noSuchMethod(
            Invocation.method(#addImageEntry, [], {
              #imageBytes: imageBytes,
              #userNote: userNote,
            }),
            returnValue:
                _i16.Future<
                  ({_i22.Entry? addedEntry, List<_i22.Entry> entries})
                >.value((addedEntry: null, entries: <_i22.Entry>[])),
          )
          as _i16.Future<({_i22.Entry? addedEntry, List<_i22.Entry> entries})>);

  @override
  _i16.Future<List<_i22.Entry>> deleteEntry(_i22.Entry? entryToDelete) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEntry, [entryToDelete]),
            returnValue: _i16.Future<List<_i22.Entry>>.value(<_i22.Entry>[]),
          )
          as _i16.Future<List<_i22.Entry>>);

  @override
  _i16.Future<List<_i22.Entry>> updateEntry(
    _i22.Entry? originalEntry,
    _i22.Entry? updatedEntry, {
    bool? skipAiRegeneration = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateEntry,
              [originalEntry, updatedEntry],
              {#skipAiRegeneration: skipAiRegeneration},
            ),
            returnValue: _i16.Future<List<_i22.Entry>>.value(<_i22.Entry>[]),
          )
          as _i16.Future<List<_i22.Entry>>);

  @override
  _i16.Future<({List<_i22.Entry> entries, int splitCount})>
  processCombinedEntry(String? combinedText, DateTime? tempEntryTimestamp) =>
      (super.noSuchMethod(
            Invocation.method(#processCombinedEntry, [
              combinedText,
              tempEntryTimestamp,
            ]),
            returnValue:
                _i16.Future<({List<_i22.Entry> entries, int splitCount})>.value(
                  (entries: <_i22.Entry>[], splitCount: 0),
                ),
          )
          as _i16.Future<({List<_i22.Entry> entries, int splitCount})>);

  @override
  _i16.Future<List<_i23.Category>> addCustomCategory(String? newCategory) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomCategory, [newCategory]),
            returnValue: _i16.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i16.Future<List<_i23.Category>>);

  @override
  _i16.Future<List<_i23.Category>> addCustomCategoryWithDescription(
    String? name,
    String? description, {
    bool? isChecklist = false,
    _i41.Color? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addCustomCategoryWithDescription,
              [name, description],
              {#isChecklist: isChecklist, #color: color},
            ),
            returnValue: _i16.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i16.Future<List<_i23.Category>>);

  @override
  _i16.Future<({List<_i23.Category> categories, List<_i22.Entry> entries})>
  deleteCategory(String? categoryToDelete) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [categoryToDelete]),
            returnValue:
                _i16.Future<
                  ({List<_i23.Category> categories, List<_i22.Entry> entries})
                >.value((
                  categories: <_i23.Category>[],
                  entries: <_i22.Entry>[],
                )),
          )
          as _i16.Future<
            ({List<_i23.Category> categories, List<_i22.Entry> entries})
          >);

  @override
  _i16.Future<bool> markEntryAsNotNew(DateTime? timestamp, String? text) =>
      (super.noSuchMethod(
            Invocation.method(#markEntryAsNotNew, [timestamp, text]),
            returnValue: _i16.Future<bool>.value(false),
          )
          as _i16.Future<bool>);

  @override
  _i16.Future<({List<_i23.Category> categories, List<_i22.Entry> entries})>
  renameCategory(
    String? oldName,
    String? newName, {
    String? description,
    bool? isChecklist,
    _i41.Color? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #renameCategory,
              [oldName, newName],
              {
                #description: description,
                #isChecklist: isChecklist,
                #color: color,
              },
            ),
            returnValue:
                _i16.Future<
                  ({List<_i23.Category> categories, List<_i22.Entry> entries})
                >.value((
                  categories: <_i23.Category>[],
                  entries: <_i22.Entry>[],
                )),
          )
          as _i16.Future<
            ({List<_i23.Category> categories, List<_i22.Entry> entries})
          >);

  @override
  _i16.Future<List<_i23.Category>> toggleCategoryArchive(
    String? categoryName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#toggleCategoryArchive, [categoryName]),
            returnValue: _i16.Future<List<_i23.Category>>.value(
              <_i23.Category>[],
            ),
          )
          as _i16.Future<List<_i23.Category>>);

  @override
  String getAllEntriesAsLogContext() =>
      (super.noSuchMethod(
            Invocation.method(#getAllEntriesAsLogContext, []),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.method(#getAllEntriesAsLogContext, []),
            ),
          )
          as String);

  @override
  _i16.Future<void> onUserSignedIn(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#onUserSignedIn, [uid]),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> loadMoreEntries() =>
      (super.noSuchMethod(
            Invocation.method(#loadMoreEntries, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> refreshFromCloud() =>
      (super.noSuchMethod(
            Invocation.method(#refreshFromCloud, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<void> onUserSignedOut() =>
      (super.noSuchMethod(
            Invocation.method(#onUserSignedOut, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<String?> downloadCloudImage(_i22.Entry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#downloadCloudImage, [entry]),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  _i16.Future<String?> ensureImageAvailable(_i22.Entry? entry) =>
      (super.noSuchMethod(
            Invocation.method(#ensureImageAvailable, [entry]),
            returnValue: _i16.Future<String?>.value(),
          )
          as _i16.Future<String?>);

  @override
  String exportToJson() =>
      (super.noSuchMethod(
            Invocation.method(#exportToJson, []),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.method(#exportToJson, []),
            ),
          )
          as String);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirebaseStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseStorage extends _i1.Mock implements _i14.FirebaseStorage {
  MockFirebaseStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i13.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_17(this, Invocation.getter(#app)),
          )
          as _i13.FirebaseApp);

  @override
  String get bucket =>
      (super.noSuchMethod(
            Invocation.getter(#bucket),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
          )
          as String);

  @override
  Duration get maxOperationRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxOperationRetryTime),
            returnValue: _FakeDuration_18(
              this,
              Invocation.getter(#maxOperationRetryTime),
            ),
          )
          as Duration);

  @override
  Duration get maxUploadRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxUploadRetryTime),
            returnValue: _FakeDuration_18(
              this,
              Invocation.getter(#maxUploadRetryTime),
            ),
          )
          as Duration);

  @override
  Duration get maxDownloadRetryTime =>
      (super.noSuchMethod(
            Invocation.getter(#maxDownloadRetryTime),
            returnValue: _FakeDuration_18(
              this,
              Invocation.getter(#maxDownloadRetryTime),
            ),
          )
          as Duration);

  @override
  set app(_i13.FirebaseApp? _app) => super.noSuchMethod(
    Invocation.setter(#app, _app),
    returnValueForMissingStub: null,
  );

  @override
  set bucket(String? _bucket) => super.noSuchMethod(
    Invocation.setter(#bucket, _bucket),
    returnValueForMissingStub: null,
  );

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i14.Reference ref([String? path]) =>
      (super.noSuchMethod(
            Invocation.method(#ref, [path]),
            returnValue: _FakeReference_19(
              this,
              Invocation.method(#ref, [path]),
            ),
          )
          as _i14.Reference);

  @override
  _i14.Reference refFromURL(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#refFromURL, [url]),
            returnValue: _FakeReference_19(
              this,
              Invocation.method(#refFromURL, [url]),
            ),
          )
          as _i14.Reference);

  @override
  void setMaxOperationRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxOperationRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setMaxUploadRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxUploadRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  void setMaxDownloadRetryTime(Duration? time) => super.noSuchMethod(
    Invocation.method(#setMaxDownloadRetryTime, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i16.Future<void> useStorageEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #useStorageEmulator,
              [host, port],
              {#automaticHostMapping: automaticHostMapping},
            ),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);
}

/// A class which mocks [Reference].
///
/// See the documentation for Mockito's code generation for more information.
class MockReference extends _i1.Mock implements _i14.Reference {
  MockReference() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_20(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i14.FirebaseStorage);

  @override
  String get bucket =>
      (super.noSuchMethod(
            Invocation.getter(#bucket),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.getter(#bucket),
            ),
          )
          as String);

  @override
  String get fullPath =>
      (super.noSuchMethod(
            Invocation.getter(#fullPath),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.getter(#fullPath),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i26.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  _i14.Reference get root =>
      (super.noSuchMethod(
            Invocation.getter(#root),
            returnValue: _FakeReference_19(this, Invocation.getter(#root)),
          )
          as _i14.Reference);

  @override
  _i14.Reference child(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#child, [path]),
            returnValue: _FakeReference_19(
              this,
              Invocation.method(#child, [path]),
            ),
          )
          as _i14.Reference);

  @override
  _i16.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i16.Future<void>.value(),
            returnValueForMissingStub: _i16.Future<void>.value(),
          )
          as _i16.Future<void>);

  @override
  _i16.Future<String> getDownloadURL() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadURL, []),
            returnValue: _i16.Future<String>.value(
              _i26.dummyValue<String>(
                this,
                Invocation.method(#getDownloadURL, []),
              ),
            ),
          )
          as _i16.Future<String>);

  @override
  _i16.Future<_i14.FullMetadata> getMetadata() =>
      (super.noSuchMethod(
            Invocation.method(#getMetadata, []),
            returnValue: _i16.Future<_i14.FullMetadata>.value(
              _FakeFullMetadata_21(this, Invocation.method(#getMetadata, [])),
            ),
          )
          as _i16.Future<_i14.FullMetadata>);

  @override
  _i16.Future<_i14.ListResult> list([_i14.ListOptions? options]) =>
      (super.noSuchMethod(
            Invocation.method(#list, [options]),
            returnValue: _i16.Future<_i14.ListResult>.value(
              _FakeListResult_22(this, Invocation.method(#list, [options])),
            ),
          )
          as _i16.Future<_i14.ListResult>);

  @override
  _i16.Future<_i14.ListResult> listAll() =>
      (super.noSuchMethod(
            Invocation.method(#listAll, []),
            returnValue: _i16.Future<_i14.ListResult>.value(
              _FakeListResult_22(this, Invocation.method(#listAll, [])),
            ),
          )
          as _i16.Future<_i14.ListResult>);

  @override
  _i16.Future<_i18.Uint8List?> getData([int? maxSize = 10485760]) =>
      (super.noSuchMethod(
            Invocation.method(#getData, [maxSize]),
            returnValue: _i16.Future<_i18.Uint8List?>.value(),
          )
          as _i16.Future<_i18.Uint8List?>);

  @override
  _i14.UploadTask putData(
    _i18.Uint8List? data, [
    _i14.SettableMetadata? metadata,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#putData, [data, metadata]),
            returnValue: _FakeUploadTask_23(
              this,
              Invocation.method(#putData, [data, metadata]),
            ),
          )
          as _i14.UploadTask);

  @override
  _i14.UploadTask putBlob(dynamic blob, [_i14.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putBlob, [blob, metadata]),
            returnValue: _FakeUploadTask_23(
              this,
              Invocation.method(#putBlob, [blob, metadata]),
            ),
          )
          as _i14.UploadTask);

  @override
  _i14.UploadTask putFile(_i30.File? file, [_i14.SettableMetadata? metadata]) =>
      (super.noSuchMethod(
            Invocation.method(#putFile, [file, metadata]),
            returnValue: _FakeUploadTask_23(
              this,
              Invocation.method(#putFile, [file, metadata]),
            ),
          )
          as _i14.UploadTask);

  @override
  _i14.UploadTask putString(
    String? data, {
    _i14.PutStringFormat? format = _i14.PutStringFormat.raw,
    _i14.SettableMetadata? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putString,
              [data],
              {#format: format, #metadata: metadata},
            ),
            returnValue: _FakeUploadTask_23(
              this,
              Invocation.method(
                #putString,
                [data],
                {#format: format, #metadata: metadata},
              ),
            ),
          )
          as _i14.UploadTask);

  @override
  _i16.Future<_i14.FullMetadata> updateMetadata(
    _i14.SettableMetadata? metadata,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateMetadata, [metadata]),
            returnValue: _i16.Future<_i14.FullMetadata>.value(
              _FakeFullMetadata_21(
                this,
                Invocation.method(#updateMetadata, [metadata]),
              ),
            ),
          )
          as _i16.Future<_i14.FullMetadata>);

  @override
  _i14.DownloadTask writeToFile(_i30.File? file) =>
      (super.noSuchMethod(
            Invocation.method(#writeToFile, [file]),
            returnValue: _FakeDownloadTask_24(
              this,
              Invocation.method(#writeToFile, [file]),
            ),
          )
          as _i14.DownloadTask);
}
