// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTjMZ8ooyZ4npJJKQ8dwDVLPtq47lssJk',
    appId: '1:951334134238:android:9e8f8a85cb37d52d74fd4f',
    messagingSenderId: '951334134238',
    projectId: 'log-splitter-mobile',
    storageBucket: 'log-splitter-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqJsR5lZ-bDyerzBnJd8y_m8Ez8mTtkuY',
    appId: '1:951334134238:ios:48fc671c1de63bd574fd4f',
    messagingSenderId: '951334134238',
    projectId: 'log-splitter-mobile',
    storageBucket: 'log-splitter-mobile.firebasestorage.app',
    androidClientId: '951334134238-lv0vdvh8pgm7vl97g637smhgjkbch4l5.apps.googleusercontent.com',
    iosClientId: '951334134238-q0medhn1p2ch2ek0pgd3p0li8qar88ju.apps.googleusercontent.com',
    iosBundleId: 'com.andrewbertino.myapp',
  );

}