default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "4CDU8HNC35",
      issuer_id: "e7791fa9-68d5-46bc-99a4-03d888c2326e",
      key_filepath: "./fastlane/AuthKey_4CDU8HNC35.p8"
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/myapp.ipa",
      skip_waiting_for_build_processing: true,
      distribute_external: true,
      groups: ["Internal Testers", "Beta Testers!"]
    )
  end

  desc "Deploy to TestFlight with changelog"
  lane :beta_with_changelog do |options|
    api_key = app_store_connect_api_key(
      key_id: "4CDU8HNC35",
      issuer_id: "e7791fa9-68d5-46bc-99a4-03d888c2326e",
      key_filepath: "./fastlane/AuthKey_4CDU8HNC35.p8"
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: "../build/ios/ipa/myapp.ipa",
      skip_waiting_for_build_processing: true,
      distribute_external: true,
      groups: ["Internal Testers", "Beta Testers!"],
      changelog: options[:changelog] || "Bug fixes and improvements"
    )
  end
end
